### ISSUE TITLE
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'

### ISSUE THREAD

**Issue by edanweis** [dbetm/handwritten-flowchart-with-cnn#24]
I get this error when running handler.py after following installation instructions.

```
File "/home/ew/anaconda3/envs/tt/lib/python3.9/site-packages/numba/targets/codegen.py", line 621, in _init
    tm = target.create_target_machine(**tm_options)
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'
```

**Comment by edanweis** [comment]
Are you aware of any newer techniques for this? vision transformer based sketch/chart recognition?

**Comment by dbetm** [comment]
Hey @edanweis 

You can try this: https://github.com/rapidsai/cuml/issues/2389#issuecomment-642645437

**Comment by dbetm** [comment]
Unfortunately I don't know new approaches for this problem, but I'm sure that the art state is much better than this project.
