### ISSUE TITLE
Training 

### ISSUE THREAD

**Issue by parthusun8** [dbetm/handwritten-flowchart-with-cnn#45]
I am able to successfully train the model by running the shape_model.py file.
A new folder gets created inside the training_results folder.

But when I run the report.py file with the dataset path and model path, The mAP calculated always comes out to be 1.0.

I need some help in this part. Please help
Below is a reason I think the model is not getting trained. But I need help to fix it. Could you please suggest some way to correct this error?

![image](https://github.com/dbetm/handwritten-flowchart-with-cnn/assets/77690791/abdf43e8-ab97-431a-8f87-8494e74477ec)

**Comment by dbetm** [comment]
Yeah, I think there is something with the training process...can you confirm that you install the dependencies using the requirements file?

**Comment by parthusun8** [comment]
Yeah
All dependencies are installed correctly. Some packages which did not get installed through requirements file were installed separately inside the virtual env

Even the input given are correct - 

![image](https://github.com/dbetm/handwritten-flowchart-with-cnn/assets/77690791/0f3e9ca9-190f-4d0b-b54c-60dc757986b2)

And The dataset folder has the following structure and is downloaded from the drive link provided in kaggle data page.
![image](https://github.com/dbetm/handwritten-flowchart-with-cnn/assets/77690791/b7b3a41c-1899-4305-9b47-6f5187e6cb6d)

**Comment by parthusun8** [comment]
The error is now resolved.
I found the issue - 

The folder was missing this model file,
I downloaded the file and then point the "input_weight_path" to this model, I was able to train the dataset.

vgg16_weights_tf_dim_ordering_tf_kernels.h5


I will close the issue, Thanks for your help previously.
Great Project!!
